server.port=8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.routes[0].id=shipment-service
spring.cloud.gateway.routes[0].uri=lb://SMART-SHIPMENT
spring.cloud.gateway.routes[0].predicates[0]=Path=/shipments/**,/api/shipments/**,/swagger-ui/**,/v3/api-docs/**

spring.cloud.gateway.routes[1].id=notification-service
spring.cloud.gateway.routes[1].uri=lb://SMART-NOTIFICATION
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/notifications/**
